FROM ubuntu:16.04
MAINTAINER Dmitry Kireev <dmitry@flotechnologies.com>


ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y -q && apt-get install -y -q \
  build-essential \
  subversion \
  git-core \
  libncurses5-dev \
  zlib1g-dev \
  gawk \
  flex \
  quilt \
  libssl-dev \
  xsltproc \
  libxml-parser-perl \
  mercurial \
  bzr \
  ecj \
  cvs \
  unzip \
  wget \
  subversion \
  python \
  xz-utils \
  sudo


WORKDIR /root/
ADD . /root/
RUN mv feeds.conf.default feeds.conf
RUN echo src-git i2cd https://github.com/FloTechnologies/icd-feed.git >> feeds.conf
RUN ./scripts/feeds update
RUN ./scripts/feeds install -a


